import type { GlobalConfig } from 'payload'

/** Field slugs match lib/cms-overlay overlay keys. */
export const Home: GlobalConfig = {
  slug: 'home',
  label: 'Homepage',
  access: { read: () => true },
  fields: [
    { name: 'hero-heading', type: 'text' },
    { name: 'hero-sub', type: 'text' },
    { name: 'hero-primary-cta', type: 'text' },
    { name: 'hero-secondary-cta', type: 'text' },
    { name: 'logos-eyebrow', type: 'text' },
    { name: 'problem-eyebrow', type: 'text' },
    { name: 'problem-heading', type: 'text' },
    { name: 'problem-body', type: 'textarea' },
    { name: 'problem-punchline', type: 'text' },
    { name: 'problem-film-caption', type: 'text' },
    { name: 'solution-eyebrow', type: 'text' },
    { name: 'solution-heading', type: 'text' },
    { name: 'solution-body', type: 'textarea' },
    { name: 'solution-claim', type: 'text' },
    { name: 'assemblies-eyebrow', type: 'text' },
    { name: 'assemblies-heading', type: 'text' },
    { name: 'assemblies-body', type: 'textarea' },
    { name: 'shell-eyebrow', type: 'text' },
    { name: 'shell-heading', type: 'text' },
    { name: 'shell-body-1', type: 'textarea' },
    { name: 'shell-body-2', type: 'textarea' },
    { name: 'who-eyebrow', type: 'text' },
    { name: 'who-heading', type: 'text' },
    { name: 'who-sub', type: 'text' },
    { name: 'who-os-title', type: 'text' },
    { name: 'footer-cta-heading', type: 'text' },
    { name: 'footer-cta-sub', type: 'text' },
    { name: 'footer-cta', type: 'text' },
    { name: 'footer-brand', type: 'text' },
    { name: 'footer-legal', type: 'text' },
  ],
}
